[package]
name = "workflows"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
fronma = "0.2.0"
reqwest = "0.12.5"
rss = "2.0.8"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
serde_yaml = "0.9.34"
tokio = {version = "1.39.2", features = ["full"]}
