name: Update JSON

on:
  workflow_dispatch:
  schedule:
    # 毎日00:00 UTCに実行します
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: cache
      uses: actions/cache@v4
      with:
        path: ./workflows/target
        key: ${{ runner.os }}-cargo-dev-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-dev-

    - name: Fetch GitHub API and update data
      run: |
        cd workflows
        cargo run

    - name: Commit and push if it changed
      run: |
        git diff
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A .
        git commit -m "update repository data" || exit 0
        git push
