name: Update JSON

on:
  workflow_dispatch:
  schedule:
    # 毎日00:00 UTCに実行します
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'

    - name: Fetch GitHub API and update JSON
      run: |
        mkdir -p ./data
        cd workflows
        npm install
        node github_repos.js > ../data/github_repos.json
        node github_commits.js > ../data/github_commits.json
        node github_releases.js > ../data/github_releases.json

    - name: Commit and push if it changed
      run: |
        git diff
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A .
        git commit -m "Update JSON data" || exit 0
        git push
