name: Update JSON

on:
  workflow_dispatch:
  schedule:
    # 毎日00:00 UTCに実行します
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'

    - name: Fetch GitHub API and update database
      run: |
        npm install
        node --loader ts-node/esm ./workflows/github_repos.js
        node --loader ts-node/esm ./workflows/github_commits.js
        node --loader ts-node/esm ./workflows/github_releases.js

    - name: Commit and push if it changed
      run: |
        git diff
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A .
        git commit -m "update repository data" || exit 0
        git push
